version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle-plugins:
        patterns:
          - "com.modrinth.minotaur"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
